/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import persistencia.AgendamentoDAO;
import entidade.Agendamento;
import entidade.Paciente;
import entidade.Servico;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import persistencia.PacienteDAO;
import persistencia.ServicoDAO;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author ma-th
 */
public class frmAlteraAgendamento extends javax.swing.JFrame {

    public String Nome, Servico;
    
    
    private String[] colunas = new String[]{"Codigo","Nome",
           "Valor"};
    
    private DefaultTableModel tmServicos = new DefaultTableModel
               (null, colunas);
    
    private List<Servico> listaServicos;
    private ListSelectionModel lsmServicos;
    
    
    private String[] colunaspaciente = new String[]{"Codigo","Nome",
           "Endereço","Telefone"};
    
    private DefaultTableModel tmPacientes = new DefaultTableModel
               (null, colunaspaciente);
    
   
    
    
    /**
     * Creates new form frmAlteraAgendamento
     */
    public frmAlteraAgendamento() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtCPFPacienteAlterar = new javax.swing.JTextField();
        txtDataNormal = new javax.swing.JTextField();
        txtRecebeDataAlterada = new javax.swing.JTextField();
        txtNomeServicoAlterar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHorarioAlterar = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtNomePacienteAlterar = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtValorServicoAlterar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDataNova = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNomeServicoAlterar.setEditable(false);

        jLabel1.setText("Paciente:");

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        jLabel2.setText("    Alteraração de Consulta");

        jLabel3.setText("Serviço:");

        try {
            txtHorarioAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:## horas")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHorarioAlterar.setToolTipText("  ");

        jLabel4.setText("Horário:");

        jLabel5.setText("Data:");

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtNomePacienteAlterar.setEditable(false);

        btnCadastrar.setText("Alterar Consulta");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtValorServicoAlterar.setEditable(false);

        jLabel6.setText("Valor Serviço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 342, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeServicoAlterar)
                            .addComponent(txtNomePacienteAlterar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 315, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHorarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDataNova, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtValorServicoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(txtNomePacienteAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeServicoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorServicoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        alterarAgendamento();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlteraAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlteraAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlteraAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlteraAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlteraAgendamento().setVisible(true);
            }
        });
    }
    
     public void recebeNome(String recebeNome){ 
       txtNomePacienteAlterar.setText(recebeNome);
   }
      public void recebeServico(String recebeServico){ 
       txtNomeServicoAlterar.setText(recebeServico);
   }
       public void recebeHora(String recebeHora){ 
       txtHorarioAlterar.setText(recebeHora);
   }
       public void recebeData(String recebeData){ 
           
       txtDataNormal.setText(recebeData);
       
       }
     public void recebeId(String recebeId){ 
       txtId.setText(recebeId);
   }
     public void recebeValor(String recebeValor){
         txtValorServicoAlterar.setText(recebeValor);
     }
       
       private void alterarAgendamento(){
      
        txtRecebeDataAlterada.setText((String.valueOf(txtDataNova)));
          
        if((txtRecebeDataAlterada.getText().isEmpty())){
            
        int opcao =  JOptionPane.showConfirmDialog(null, "Deseja alterar a consulta?","Alterar Consulta",0);
           
        if (opcao == 0){
        
        
            
        /*Date data = txtDataNormal.getDate();
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy/MM/dd");
        String novaData = formatador.format(data);*/
           
        Agendamento age = new Agendamento();
        
        
        age.setNome(txtNomePacienteAlterar.getText().trim());
        age.setCpf(txtCPFPacienteAlterar.getText().trim());
        age.setServico(txtNomeServicoAlterar.getText().trim());
        age.setValor(txtValorServicoAlterar.getText().trim());
        age.setHorario(txtHorarioAlterar.getText().trim());
        age.setData(txtDataNormal.getText());
        
        
        age.setCodigo(Integer.valueOf(txtId.getText()));
        
        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
        agendamentoDAO.alterarAgendamento(age);
        JOptionPane.showMessageDialog(this, "Consulta alterada com sucesso!");
        
        frmAgendamento ps = new frmAgendamento();
        
        String n = txtNomePacienteAlterar.getText();
       
        ps.listaAgendamentos = agendamentoDAO.listarAgendamentos("%"+
             n + "%");
        ps.mostrarAgendamentos(ps.listaAgendamentos);
        ps.listarAgendamentos();
        dispose();
        ps.setVisible(true);
       }else{
        frmAgendamento ps = new frmAgendamento();
        ps.setVisible(true);
        ps.listarAgendamentos();
        dispose();
        
        
    }
       }else{
           
     
        int opcao =  JOptionPane.showConfirmDialog(null, "Deseja alterar a consulta?","Alterar Consulta",0);
           
        if (opcao == 0){
        
        Date data = txtDataNova.getDate();
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy/MM/dd");
        String novaData = formatador.format(data);
           
        Agendamento age = new Agendamento();
        
        
        age.setNome(txtNomePacienteAlterar.getText().trim());
        age.setCpf(txtCPFPacienteAlterar.getText().trim());
        age.setServico(txtNomeServicoAlterar.getText().trim());
        age.setValor(txtValorServicoAlterar.getText().trim());
        age.setHorario(txtHorarioAlterar.getText().trim());
        age.setData(txtDataNova.getDateFormatString().format(novaData));
        
        
        age.setCodigo(Integer.valueOf(txtId.getText()));
        
        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
        agendamentoDAO.alterarAgendamento(age);
        JOptionPane.showMessageDialog(this, "Consulta alterada com sucesso!");
        
      
        
        frmAgendamento ps = new frmAgendamento();
        
        String n = txtNomePacienteAlterar.getText();
       
        ps.listaAgendamentos = agendamentoDAO.listarAgendamentos("%"+
             n + "%");
        ps.mostrarAgendamentos(ps.listaAgendamentos);
        ps.listarAgendamentos();
        dispose();
        ps.setVisible(true);
       }else{
        frmAgendamento ps = new frmAgendamento();
        ps.setVisible(true);
        ps.listarAgendamentos();
        dispose();
        }
       }
       }
       
      
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCPFPacienteAlterar;
    private javax.swing.JTextField txtDataNormal;
    private com.toedter.calendar.JDateChooser txtDataNova;
    private javax.swing.JFormattedTextField txtHorarioAlterar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomePacienteAlterar;
    private javax.swing.JTextField txtNomeServicoAlterar;
    private javax.swing.JTextField txtRecebeDataAlterada;
    private javax.swing.JTextField txtValorServicoAlterar;
    // End of variables declaration//GEN-END:variables
}
