/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import javax.swing.JTable;
import entidade.Usuario;
import persistencia.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ma-th
 */
public class frmAlterarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmAlterarUsuario
     */
    public frmAlterarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomeAlterar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoginAlterar = new javax.swing.JTextField();
        cmbStatusAlterar = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSenhaAlterar = new javax.swing.JTextField();
        cmbPermissaoAlterar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        txtId.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 73, 125));
        jLabel1.setText("ALTERAÇÃO DE USUÁRIO");

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 73, 125));
        jLabel10.setText("Permissão:");

        txtNomeAlterar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        txtNomeAlterar.setForeground(new java.awt.Color(0, 73, 125));
        txtNomeAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219), 2));
        txtNomeAlterar.setCaretColor(new java.awt.Color(0, 73, 125));

        jLabel3.setForeground(new java.awt.Color(0, 73, 125));
        jLabel3.setText("Status:");

        txtLoginAlterar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        txtLoginAlterar.setForeground(new java.awt.Color(0, 73, 125));
        txtLoginAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219), 2));
        txtLoginAlterar.setCaretColor(new java.awt.Color(0, 73, 125));
        txtLoginAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAlterarActionPerformed(evt);
            }
        });

        cmbStatusAlterar.setBackground(new java.awt.Color(0, 73, 125));
        cmbStatusAlterar.setForeground(new java.awt.Color(255, 255, 255));
        cmbStatusAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        cmbStatusAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusAlterarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 155, 219));
        btnSalvar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 155, 219));
        btnCancelar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Cancelar IMG - Sistema.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 125));
        jLabel2.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 73, 125));
        jLabel7.setText("Login:");

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 73, 125));
        jLabel8.setText("Senha:");

        txtSenhaAlterar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        txtSenhaAlterar.setForeground(new java.awt.Color(0, 73, 125));
        txtSenhaAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219), 2));
        txtSenhaAlterar.setCaretColor(new java.awt.Color(0, 73, 125));

        cmbPermissaoAlterar.setBackground(new java.awt.Color(0, 73, 125));
        cmbPermissaoAlterar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        cmbPermissaoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        cmbPermissaoAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 73, 125));
        jLabel4.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSenhaAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(txtLoginAlterar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNomeAlterar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(103, 103, 103)
                            .addComponent(jLabel3)
                            .addGap(82, 82, 82))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbPermissaoAlterar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbStatusAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPermissaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatusAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        alterarUsuario();
        frmPesquisaUsuario pu  = new frmPesquisaUsuario();
        pu.listarUsuarios();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        frmPesquisaUsuario usu = new frmPesquisaUsuario();
        usu.setVisible(true);
        usu.listarUsuarios();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtLoginAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAlterarActionPerformed

    private void cmbStatusAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlterarUsuario().setVisible(true);
            }
        });
    }

     public void recebeNome(String recebeNome){ 
       txtNomeAlterar.setText(recebeNome);
   }
     
      public void recebeLogin(String recebeLogin){ 
       txtLoginAlterar.setText(recebeLogin);
   }
      
      public void recebeSenha(String recebeSenha){ 
       txtSenhaAlterar.setText(recebeSenha);
   }
     public void recebePermissao(String recebePermissao){ 
       cmbPermissaoAlterar.setSelectedItem(recebePermissao);
   }
     public void recebeStatus(String recebeStatus){ 
       cmbStatusAlterar.setSelectedItem(recebeStatus);
   }
     public void recebeId(String recebeId){ 
       txtId.setText(recebeId);
   }
     
     public void alterarUsuario(){
          
       int opcao =  JOptionPane.showConfirmDialog(null, "Deseja alterar o usuário?","Alterar",0);
       
       if (opcao == 0){
           
        Usuario usuario = new Usuario();
         
        usuario.setNome(txtNomeAlterar.getText().trim());
        usuario.setLogin(txtLoginAlterar.getText().trim());
        usuario.setSenha(txtSenhaAlterar.getText().trim());
        usuario.setPermissao(cmbPermissaoAlterar.getSelectedItem().toString().trim());
        usuario.setStatus(cmbStatusAlterar.getSelectedItem().toString().trim());
        usuario.setCodigo(Integer.valueOf(txtId.getText()));
       
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.alterarUsuario(usuario);
        JOptionPane.showMessageDialog(null,"Usuário alterado com sucesso!","Usuário Alterado",JOptionPane.INFORMATION_MESSAGE);
        
        frmPesquisaUsuario pes = new frmPesquisaUsuario();
        
        String n = txtNomeAlterar.getText();
       
        pes.listaUsuarios = usuarioDAO.listarUsuarios("%"+
             n + "%");
        pes.mostrarUsuarios(pes.listaUsuarios);
        pes.listarUsuarios();
        dispose();
        pes.setVisible(true);
       } else if(opcao == 1){
           
        frmPesquisaUsuario usu = new frmPesquisaUsuario();
        usu.setVisible(true);
        usu.listarUsuarios();
        dispose();
           
       }
    } 
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbPermissaoAlterar;
    private javax.swing.JComboBox<String> cmbStatusAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLoginAlterar;
    private javax.swing.JTextField txtNomeAlterar;
    private javax.swing.JTextField txtSenhaAlterar;
    // End of variables declaration//GEN-END:variables
}
