/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;


import entidade.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import persistencia.UsuarioDAO;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ma-th
 */
public class frmPesquisaUsuario extends javax.swing.JFrame {

    
    frmAlterarUsuario enviar;
    
    public String[] colunas = new String[]{"Codigo","Nome",
           "Login","Permissao"};
    
    public DefaultTableModel tmUsuarios = new DefaultTableModel
               (null, colunas);
    
    public List<Usuario> listaUsuarios;
    public ListSelectionModel lsmUsuarios; 
    
    
    
    
    /**
     * Creates new form frmPesquisaUsuario
     */
    public frmPesquisaUsuario() {
        initComponents();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        cmbPermissao = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluirPaciente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPesquisarUsuarios = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();

        cmbPermissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        txtId.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Usuários");
        setUndecorated(true);
        setResizable(false);

        tblUsuarios.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tblUsuarios.setModel(tmUsuarios);
        tblUsuarios.setToolTipText("");
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmUsuarios = tblUsuarios.getSelectionModel();
        lsmUsuarios.addListSelectionListener (new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()) {
                    tblUsuariosLinhaSelecionada(tblUsuarios);
                }
            }

        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnInserir.setBackground(new java.awt.Color(0, 155, 219));
        btnInserir.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 155, 219));
        btnAlterar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Atualizar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluirPaciente.setBackground(new java.awt.Color(0, 155, 219));
        btnExcluirPaciente.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnExcluirPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Lixeira.png"))); // NOI18N
        btnExcluirPaciente.setText("Excluir");
        btnExcluirPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnExcluirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPacienteActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 155, 219));
        btnCancelar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Cancelar IMG - Sistema.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtPesquisarUsuarios.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtPesquisarUsuarios.setForeground(new java.awt.Color(0, 73, 125));
        txtPesquisarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219), 2));
        txtPesquisarUsuarios.setCaretColor(new java.awt.Color(0, 73, 125));

        btnPesquisar.setBackground(new java.awt.Color(0, 155, 219));
        btnPesquisar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/imgs/Pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 155, 219)));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 73, 125));
        jLabel1.setText("PESQUISA DE USUÁRIOS");

        lblSair.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblSair.setForeground(new java.awt.Color(0, 73, 125));
        lblSair.setText("X");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtPesquisarUsuarios)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(lblSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        new frmCadastraUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(txtNome.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Favor selecionar um usuário para alterar","Alterar Usuário",
                 JOptionPane.INFORMATION_MESSAGE);
        }else{
            enviarAlteracaoUsuario();
            listarUsuarios();
            dispose();
        }        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        listarUsuarios();
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPacienteActionPerformed
        // TODO add your handling code here:
        if(txtNome.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Favor selecionar um usuário para excluir","Excluir Usuário",
                 JOptionPane.INFORMATION_MESSAGE);
        }else{
        excluirUsuario();
        listarUsuarios();
    }//GEN-LAST:event_btnExcluirPacienteActionPerformed
    }
    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        btnAlterar.setEnabled(true);
        btnExcluirPaciente.setEnabled(true);
        btnInserir.setEnabled(true);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lblSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPesquisaUsuario().setVisible(true);
            }
        });
    }

    
    public void mostrarUsuarios(List<Usuario> usuarios){
        
        while (tmUsuarios.getRowCount() > 0){
            tmUsuarios.removeRow(0);
        }
        if(usuarios.size() == 0){
            JOptionPane.showMessageDialog(this, "Nenhum usuario foi encontrado!");
        }else{
            
             for (int i = 0; i < usuarios.size(); i++){
                tmUsuarios.addRow(colunas);
                tmUsuarios.setValueAt(usuarios.get(i).getCodigo(), i,0);
                tmUsuarios.setValueAt(usuarios.get(i).getNome(), i,1);
                tmUsuarios.setValueAt(usuarios.get(i).getLogin(), i,2);
                tmUsuarios.setValueAt(usuarios.get(i).getPermissao(), i,3);
                
            }
        }
    }
    
     
    
    public void listarUsuarios(){
        
        UsuarioDAO usuarioDAO =  new UsuarioDAO();
        listaUsuarios = usuarioDAO.listarUsuarios("%"
             +txtPesquisarUsuarios.getText().trim() + "%");
        mostrarUsuarios(listaUsuarios);
        
    }
    
    
    private void excluirUsuario(){
        
          int excluir;
          
          excluir = JOptionPane.showConfirmDialog(null,"Deseja excluir esse usuario ?","Excluir Usuario",0);
          
          if(excluir == 0){
              
        Usuario usuario = new Usuario();
        usuario.setCodigo(listaUsuarios.get(tblUsuarios.getSelectedRow()).getCodigo());
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.excluirUsuario(usuario);
        JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
        
        dispose();
     
        setVisible(true);
        listarUsuarios();     
    }
     
     }
    
     public void tblUsuariosLinhaSelecionada(JTable tbl){
        
            int linhaSelecionada = tbl.getSelectedRow();
            
             if (linhaSelecionada != -1){
            
             txtNome.setText(listaUsuarios.get(linhaSelecionada).getNome());
             txtLogin.setText(listaUsuarios.get(linhaSelecionada).getLogin());
             txtSenha.setText(listaUsuarios.get(linhaSelecionada).getSenha());
             cmbPermissao.setSelectedItem(listaUsuarios.get(linhaSelecionada).getPermissao());
             cmbStatus.setSelectedItem(listaUsuarios.get(linhaSelecionada).getStatus());
             txtId.setText(String.valueOf(listaUsuarios.get(linhaSelecionada).getCodigo()));
             
             }
        }
     
     public void enviarAlteracaoUsuario(){
              if(enviar==null){
           
            
            enviar = new frmAlterarUsuario();
            enviar.setVisible(true);
            enviar.recebeNome(txtNome.getText());
            enviar.recebeLogin(txtLogin.getText());
            enviar.recebeSenha(txtSenha.getText());
            enviar.recebePermissao((String) cmbPermissao.getSelectedItem());
            enviar.recebeStatus((String) cmbStatus.getSelectedItem());
            enviar.recebeId(txtId.getText());
            
            
        }else{
             
                  
            enviar = new frmAlterarUsuario();
            enviar.setVisible(true);
            enviar.recebeNome(txtNome.getText());
            enviar.recebeLogin(txtLogin.getText());
            enviar.recebeSenha(txtSenha.getText());
            enviar.recebePermissao((String) cmbPermissao.getSelectedItem());
            enviar.recebeStatus((String) cmbStatus.getSelectedItem());
            enviar.recebeId(txtId.getText());
            enviar.setState(frmAlterarUsuario.NORMAL);
             
          }
      
          }
          
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirPaciente;
    private javax.swing.JButton btnInserir;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbPermissao;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSair;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisarUsuarios;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
