/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import javax.swing.JOptionPane;

/**
 *
 * @author ma-th
 */
public class frmTelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form frmTelaPrincipal
     */
    public frmTelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void Sair(){
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "SAIR DO SISTEMA", 0, JOptionPane.OK_CANCEL_OPTION);
        if(opcao == 0){
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Voltando ao sistema em 3... 2... 1!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAgendamento = new javax.swing.JMenu();
        mnuCadastros = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuServicos = new javax.swing.JMenuItem();
        mnuRelatorio = new javax.swing.JMenu();
        mnuConfiguracoes = new javax.swing.JMenu();
        mnuCadastroUsuario = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Health For You");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desenvolvido por Health Solutions");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(940, 1060, 181, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\joao-\\Desktop\\2systemonemore.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 240, 540, 190);

        jMenuBar1.setForeground(new java.awt.Color(51, 102, 255));
        jMenuBar1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        mnuAgendamento.setText("Agendamento");
        mnuAgendamento.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAgendamentoMouseClicked(evt);
            }
        });
        mnuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgendamentoActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuAgendamento);

        mnuCadastros.setText("Cadastros");
        mnuCadastros.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        mnuClientes.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuClientes.setText("Pacientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuClientes);

        mnuServicos.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuServicos.setText("Serviços");
        mnuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServicosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuServicos);

        jMenuBar1.add(mnuCadastros);

        mnuRelatorio.setText("Relatórios");
        mnuRelatorio.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jMenuBar1.add(mnuRelatorio);

        mnuConfiguracoes.setText("Configurações");
        mnuConfiguracoes.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        mnuCadastroUsuario.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuCadastroUsuario.setText("Usuários");
        mnuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroUsuarioActionPerformed(evt);
            }
        });
        mnuConfiguracoes.add(mnuCadastroUsuario);

        mnuSobre.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnuConfiguracoes.add(mnuSobre);

        jMenuBar1.add(mnuConfiguracoes);

        mnuSair.setText("Sair");
        mnuSair.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        // TODO add your handling code here:
        new frmPesquisarCliente().setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        Sair();
    }//GEN-LAST:event_mnuSairMouseClicked

    private void mnuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServicosActionPerformed
        // TODO add your handling code here:
        new frmPesquisaServico().setVisible(true);
    }//GEN-LAST:event_mnuServicosActionPerformed

    private void mnuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        new frmPesquisaUsuario().setVisible(true);
    }//GEN-LAST:event_mnuCadastroUsuarioActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sistema desenvolvido por Health Solutions" 
                + "\n - Igor, João Paulo, Matheus Alves, Matheus Gontijo e Túlio "
                + "\n - 2018, Una Bom Despacho", "Sobre Nós", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void mnuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgendamentoActionPerformed
        // TODO add your handling code here:
        new frmAgendamento().setVisible(true);
    }//GEN-LAST:event_mnuAgendamentoActionPerformed

    private void mnuAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAgendamentoMouseClicked
        // TODO add your handling code here:
        new frmAgendamento().setVisible(true);
    }//GEN-LAST:event_mnuAgendamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAgendamento;
    private javax.swing.JMenuItem mnuCadastroUsuario;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenu mnuConfiguracoes;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenuItem mnuServicos;
    private javax.swing.JMenuItem mnuSobre;
    // End of variables declaration//GEN-END:variables
}
